### ISSUE TITLE
Generated travis.yml does not handle minimum PHP version correctly in some cases

### ISSUE THREAD

**Issue by sgiehl** [piwik/travis-scripts#32]
When defining `5.5.9` as minimum PHP requirement in a plugin.json, the generated `travis.yml` file will use `5.5` as PHP version to test against, but in the block of excluded tests, still the original value will be used

```yml
language: php

php:
  - 5.6
  - 5.5
#  - hhvm
```
....
```yml

matrix:
  exclude:
    # execute latest stable tests only w/ PHP 5.5
    - php: 5.5.9
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_CORE=minimum_required_piwik
    # execute UI tests only w/ PHP 5.6
    - php: 5.5.9
      env: TEST_SUITE=UITests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_TEST_TARGET

sudo: required
```
